import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Layout({children, title}){
    return(
        <>
        <Head>
        <title>{title ? title+'-Amazon': 'Amazon'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
        <div className='flex min-h-screen flex-col justify-between'>
            <header>
                <nav className='flex h-12 item-center px-4 justify-between shadow-md'>
                    <Link legacyBehavior href="/">
                        <a className='text-lg font-bold'>amazon</a>
                    </Link>
                    <div>
                        <Link  legacyBehavior href="/cart"><a className="p-2">Cart</a></Link>
                        <Link legacyBehavior href="/login"><a className="p-2">Login</a></Link>
                    </div>
                </nav>
            </header>
            <main className="container m-auto mt-4 px-4">
                {children}

            </main>
            <footer className="flex h-10 justify-center items-center shadow-inner">
                <p>Copyright 2023 Amazon</p>

            </footer>
        </div>
       
        </>
    )
}